import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import MockupStyle from "../components/MockupStyle";
import css from "../mockups/comunicacao.css?raw";
import { useAuth } from "../contexts/auth";
import type { AlunoApi } from "./comunicacao/model";
import { criarGrupos, formatarPrazo, normalizarEmail } from "./comunicacao/utils";
import { useHistoricoComunicacao } from "./comunicacao/hooks/useHistoricoComunicacao";
import { criarTextoEmail } from "./comunicacao/mensagens";

function fmtData(s:string){const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleString("pt-BR")}
async function copy(text:string){if(navigator.clipboard)await navigator.clipboard.writeText(text)}
export default function Comunicacao(){
 const {modoApresentacao}=useAuth();
 const [alunos,setAlunos]=useState<AlunoApi[]>([]),[unidade,setUnidade]=useState("TODAS"),[unitOpen,setUnitOpen]=useState(false),[buscaGrupo,setBuscaGrupo]=useState(""),[buscaAluno,setBuscaAluno]=useState(""),[grupoKey,setGrupoKey]=useState(""),[selecionados,setSelecionados]=useState<Set<string>>(new Set()),[prazo,setPrazo]=useState("01/07"),[assunto,setAssunto]=useState("Documentação pendente - Matricula"),[feedback,setFeedback]=useState("");
 const buscaAlunoAdiada=useDeferredValue(buscaAluno);
 const [limiteAlunosGrupo,setLimiteAlunosGrupo]=useState(60);
 const sentinelaAlunosGrupoRef=useRef<HTMLLIElement|null>(null);
 const {historico,historicoErro,registrandoHistorico,carregarHistorico,registrarCobranca}=useHistoricoComunicacao();
 useEffect(()=>{fetch("/api/alunos").then(r=>r.ok?r.json() as Promise<AlunoApi[]>:Promise.reject()).then(setAlunos).catch(()=>setAlunos([]))},[]);
 const unidades=useMemo(()=>["EAD","FACE","FCH","FEA"].map(u=>({u,total:alunos.filter(a=>a.unidade===u).length})),[alunos]);
 const grupos=useMemo(()=>{const base=unidade==="TODAS"?alunos:alunos.filter(a=>a.unidade===unidade);const q=buscaGrupo.trim().toLowerCase();return criarGrupos(base).filter(g=>!q||g.documentos.some(d=>d.curto.toLowerCase().includes(q)))},[alunos,unidade,buscaGrupo]);
 useEffect(()=>{if(!grupos.length){setGrupoKey("");return}if(!grupos.some(g=>g.chave===grupoKey))setGrupoKey(grupos[0].chave)},[grupos,grupoKey]);
 const grupo=grupos.find(g=>g.chave===grupoKey);
 const cobrancasGrupo=useMemo(()=>historico.filter(h=>h.grupo_chave===grupo?.chave),[historico,grupo?.chave]);
 const cobrancasPorRa=useMemo(()=>{const m=new Map<string,{q:number,ultima:string}>();for(const h of cobrancasGrupo)for(const ra of h.ras||[]){const x=m.get(ra);if(x){x.q++;if(new Date(h.criado_em)>new Date(x.ultima))x.ultima=h.criado_em}else m.set(ra,{q:1,ultima:h.criado_em})}return m},[cobrancasGrupo]);
 useEffect(()=>{if(!grupo){setSelecionados(new Set());return}setSelecionados(new Set(grupo.alunos.filter(a=>!cobrancasPorRa.has(a.ra)).map(a=>a.ra)));setBuscaAluno("")},[grupo?.chave,cobrancasPorRa]);
 const alunosSel=grupo?.alunos.filter(a=>selecionados.has(a.ra))||[];
 const inst=[...new Set(alunosSel.map(a=>normalizarEmail(a.email)).filter(Boolean))]; const alt=[...new Set(alunosSel.map(a=>normalizarEmail(a.email_outro)).filter(Boolean))];
 const semInst=alunosSel.filter(a=>!normalizarEmail(a.email)).length; const invalidos=alunosSel.map(a=>(a.email||"").trim()).filter(Boolean).filter(e=>!normalizarEmail(e)).length; const brutos=alunosSel.map(a=>(a.email||"").trim()).filter(Boolean);const duplicados=brutos.length-new Set(brutos.map(e=>e.toLowerCase())).size;
 const ja=grupo?.alunos.filter(a=>cobrancasPorRa.has(a.ra)).length||0, nao=(grupo?.alunos.length||0)-ja;
 const visible=grupo?.alunos.filter(a=>{const q=buscaAlunoAdiada.trim().toLowerCase();return !q||`${a.nome} ${a.ra} ${a.curso} ${a.email||""} ${a.email_outro||""}`.toLowerCase().includes(q)})||[];
 const visibleLimitados=visible.slice(0,limiteAlunosGrupo);
 const temMaisAlunosGrupo=limiteAlunosGrupo<visible.length;
 useEffect(()=>{setLimiteAlunosGrupo(60)},[grupo?.chave,buscaAlunoAdiada]);
 useEffect(()=>{
  const alvo=sentinelaAlunosGrupoRef.current;
  if(!alvo||!temMaisAlunosGrupo)return;
  const observer=new IntersectionObserver((entradas)=>{
   if(entradas[0]?.isIntersecting)setLimiteAlunosGrupo(v=>Math.min(v+60,visible.length));
  },{root:alvo.closest(".student-check-list"),rootMargin:"240px 0px"});
  observer.observe(alvo);
  return()=>observer.disconnect();
 },[temMaisAlunosGrupo,visible.length]);
 const texto=criarTextoEmail(grupo,prazo);
 async function registrar(){if(!grupo||!alunosSel.length)return;await registrarCobranca({grupo_chave:grupo.chave,unidade,documentos:grupo.documentos.map(d=>d.curto),quantidade_alunos:alunosSel.length,quantidade_emails:inst.length,assunto,prazo,tipo_destinatario:"institucional",ras:alunosSel.map(a=>a.ra)});setFeedback("✓ Cobrança registrada no histórico.")}
 const nomeGrupo=grupo?(grupo.documentos.length===7?"Todos os documentos":grupo.documentos.length===1?`1 documento pendente — ${grupo.documentos[0].curto}`:`${grupo.documentos.length} documentos pendentes`):"—";
 return <><MockupStyle css={css}/><div className="page-head"><h1>Comunicação</h1><p>Grupos automáticos por combinação exata de pendências.</p></div><div className="tabs"><div className="tab active">Cobranças</div><div className="tab">{grupos.length} combinações</div></div>
 <div className="comm-top-grid"><div><div className="field-label">Unidade</div><div className={`unit-filter${unitOpen?" open":""}`}><div className="filter-row" onClick={()=>setUnitOpen(v=>!v)}><span>{unidade==="TODAS"?"Todas as unidades":unidade}</span><span className="chev"/></div><div className="unit-filter-panel"><div className="ufp-head">Filtrar por unidade</div><ul><li className={unidade==="TODAS"?"selected":""} onClick={()=>{setUnidade("TODAS");setUnitOpen(false)}}><span className="radio"/><span className="uf-label">Todas as unidades</span><span className="uf-count">{alunos.length.toLocaleString("pt-BR")}</span></li>{unidades.map(x=><li key={x.u} className={unidade===x.u?"selected":""} onClick={()=>{setUnidade(x.u);setUnitOpen(false)}}><span className="radio"/><span className="uf-label">{x.u}</span><span className="uf-count">{x.total}</span></li>)}</ul></div></div><div className="search-row"><div className="search-input"><span className="icon">⌕</span><input value={buscaGrupo} onChange={e=>setBuscaGrupo(e.target.value)} placeholder="Ex.: Contrato, CPF, Histórico..."/></div></div><div className="col-head">Combinações exatas</div><ul className="combo-list">{grupos.map(g=><li className={`combo-item${g.chave===grupoKey?" selected":""}`} key={g.chave} onClick={()=>setGrupoKey(g.chave)}><div className="ci-row"><div><div className={`ci-name${g.documentos.length===7?" strong":""}`}>{g.documentos.length===7?"Todos os documentos":`${g.documentos.length} documento${g.documentos.length===1?"":"s"} pendente${g.documentos.length===1?"":"s"}`}</div>{g.documentos.length!==7&&<div className="ci-pills">{g.documentos.map(d=><span key={d.campo} className={`doc-p ${d.prioritario?"terracotta":"amber"}`}>{d.curto}</span>)}</div>}<div className="ci-sub">{g.alunos.length} aluno{g.alunos.length===1?"":"s"}</div></div><div className="ci-count">{g.alunos.length}</div></div></li>)}</ul></div>
 <div className="combo-detail">{grupo&&<><h3>{grupo.documentos.length===7?"Todos os documentos":nomeGrupo}</h3><p className="cd-desc">Aqui entram somente alunos que devem exatamente estes documentos — nenhum a mais e nenhum a menos.</p><p className="cd-stat good">{ja} já cobrado(s)</p><p className="cd-stat warning">{nao} ainda não cobrado(s)</p><p className="cd-last">{cobrancasGrupo[0]?`Última cobrança: ${fmtData(cobrancasGrupo[0].criado_em)}`:"Nenhuma cobrança registrada"}</p><div className="cd-pills">{grupo.documentos.map(d=><span className={`doc-p ${d.prioritario?"terracotta":"amber"}`} key={d.campo}>{d.curto}{d.prioritario?" · prioritário":""}</span>)}</div></>}</div>
 <div className="combo-history"><div className="ch-head"><div className="col-head" style={{marginBottom:0}}>Histórico de cobranças</div><a className="refresh-link" style={{fontSize:"0.78rem"}} onClick={()=>void carregarHistorico()}>↻ Atualizar</a></div><h3>Últimos registros</h3>{historicoErro?<div className="log-sub">{historicoErro}</div>:<ul className="log-list">{historico.slice(0,12).map(h=><li className="log-item" key={h.id}><div><div className="log-name">{h.documentos.length===7?"Todos os documentos":h.documentos.join(" + ")}</div><div className="log-sub">{h.unidade==="TODAS"?"Todas as unidades":h.unidade} • {fmtData(h.criado_em)}</div></div><div className="log-stats"><div className="log-stat"><strong>{h.quantidade_alunos}</strong><span>alunos</span></div><div className="log-stat"><strong>{h.quantidade_emails}</strong><span>e-mails</span></div></div></li>)}</ul>}</div></div>
 <div className="comm-section"><div className="col-head">Destinatários</div><p className="dest-count">{alunosSel.length} alunos selecionados</p><p className="dest-sub">{inst.length} com e-mail institucional • {semInst} sem institucional • {alt.length} alternativos</p>{!modoApresentacao&&<div className="dest-actions"><a onClick={()=>void copy(inst.join("; "))}>Copiar institucionais</a><a onClick={()=>void copy(alt.join("; "))}>Copiar alternativos</a><a onClick={()=>void copy([...new Set([...inst,...alt])].join("; "))}>Copiar ambos</a><a onClick={()=>void copy(`CCO:\n${inst.join("; ")}\n\nASSUNTO:\n${assunto}\n\nMENSAGEM:\n${texto}`)}>Copiar pacote</a><a onClick={()=>void registrar()}>{registrandoHistorico?"Registrando...":"Registrar cobrança"}</a></div>}<div className="col-head">Validação dos destinatários</div><p className="validation-ready">{semInst===0&&invalidos===0?"Lista pronta para comunicação":"Revise a lista antes da comunicação"}</p><div className="validation-checks"><span className="v-check"><span className="check">✓</span>{semInst} sem e-mail institucional</span><span className="v-check"><span className="check">✓</span>{invalidos} e-mail(is) inválido(s)</span><span className="v-check"><span className="check">✓</span>{duplicados} duplicado(s)</span></div>{feedback&&<p className="dest-sub" style={{marginTop:"1rem",color:"var(--teal)"}}>{feedback}</p>}</div>
 <div className="comm-bottom-grid"><div><div className="msg-field-row"><label className="field short"><span>Data limite <span style={{fontWeight:400,color:"var(--muted)",textTransform:"none"}}>(dd/mm)</span></span><input value={prazo} onChange={e=>setPrazo(formatarPrazo(e.target.value))}/></label><label className="field"><span>Assunto</span><input value={assunto} onChange={e=>setAssunto(e.target.value)}/></label></div><div className="msg-copy-links"><a onClick={()=>void copy(assunto)}>Copiar assunto</a><a onClick={()=>void copy(texto)}>Copiar texto</a></div><div className="col-head">Prévia da mensagem</div><div className="msg-preview"><p><span className="msg-warn">⚠ ATENÇÃO! NÃO RESPONDER A ESTE E-MAIL.</span> MANDE A SUA RESPOSTA PARA O E-MAIL ABAIXO 📧:</p><p><a className="msg-link">matriculadecalouro@fumec.edu.br</a></p><p>Prezado(a), boa tarde.</p><p>Informo que em verificação ao nosso sistema a sua matrícula está pendente alguns documentos importantes. Peço que realize o envio dos mesmos o mais rápido possível via e-mail para <a className="msg-link">matriculadecalouro@fumec.edu.br</a> ou, se preferir, pode comparecer pessoalmente na secretaria acadêmica até o dia {prazo}. Informo que a não apresentação destes documentos poderá resultar no bloqueio da sua matrícula. Segue lista abaixo:</p><ul>{grupo?.documentos.map(d=><li key={d.campo} className={d.prioritario?"priority":""}>{d.email.replace(" (DOCUMENTO PRIORITÁRIO)","")}{d.prioritario?" (documento prioritário)":""};</li>)}</ul>{grupo?.documentos.some(d=>d.campo==="contrato")&&<p>Caso esteja pendente o <a className="msg-contract-link">CONTRATO DE MATRÍCULA</a> assinado, você irá receber no seu e-mail um link para o portal de visualização e assinatura do contrato. Caso contrário, desconsidere as orientações.</p>}</div></div>
 <div><div className="students-head"><h4>Alunos do grupo</h4><span className="students-count">{alunosSel.length}/{grupo?.alunos.length||0} selecionados</span></div><div className="search-row" style={{marginBottom:0}}><div className="search-input"><span className="icon">⌕</span><input value={buscaAluno} onChange={e=>setBuscaAluno(e.target.value)} placeholder="Nome, RA, curso ou e-mail"/></div></div><div className="students-actions"><a onClick={()=>setSelecionados(new Set(grupo?.alunos.map(a=>a.ra)||[]))}>Selecionar todos</a><a onClick={()=>setSelecionados(new Set(grupo?.alunos.filter(a=>!cobrancasPorRa.has(a.ra)).map(a=>a.ra)||[]))}>Selecionar não cobrados</a><a onClick={()=>setSelecionados(new Set())}>Limpar seleção</a></div><ul className="student-check-list">{visibleLimitados.map(a=>{const charged=cobrancasPorRa.get(a.ra);return <li className="student-check-row" key={a.ra}><input type="checkbox" checked={selecionados.has(a.ra)} onChange={()=>setSelecionados(s=>{const n=new Set(s);if(n.has(a.ra))n.delete(a.ra);else n.add(a.ra);return n})}/><div className="sc-main"><div className="sc-name">{a.nome.toUpperCase()}</div><div className="sc-meta">RA {a.ra}<span className="sep">•</span>{a.curso.toUpperCase()}<span className="sep">•</span>{a.unidade}</div><div className="sc-emails">{a.email||"—"} <span className="sep">•</span> {a.email_outro||"—"}</div>{charged?<div className="sc-badge">✓ Cobrado em {fmtData(charged.ultima)} • {charged.q}x</div>:<div className="sc-badge pending">Ainda não cobrado</div>}</div></li>})}{temMaisAlunosGrupo&&<li ref={sentinelaAlunosGrupoRef} aria-hidden="true" style={{height:1,padding:0,border:0}}/>}</ul></div></div>
 </>;
}
